apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: MY_ENV
          value: "Hola mundo"
      resources:
        # Recursos mínimos
        requests:
          memory: '64Mi'
          cpu: '200m'
        # Recursos máximos
        limits:
          memory: '100Mi'
          cpu: '500m'